### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by Farrukh381** [housamz/php-mysql-admin-panel-generator#1]
when i click the next button nothing works......fix the issue mate

**Comment by yoyox221** [comment]
when I click the next button nothing works

**Comment by ocingillioglu** [comment]
when I click the next button nothing works

**Comment by jessetechno** [comment]
Same issue.  Click Next after entering DB login... Nothing.  I'm showing an error that says the handler.php is not there but it is there.

**Comment by tej-kweku** [comment]
It has to do with the mysql functions employed. You have got to change 

- all `mysql` functions into `mysqli` functions
- then `mysqli_error()` calls to `mysqli_error($link)`

From then, everything would work fine

**Comment by tej-kweku** [comment]
From the `mysql` functions used, it can be deduced that the project was written to work with `Php 5*`. Thus if your system (computer) is set to use `Php 7*` you would have this issue as the all `mysql` functions used in this project have been deprecated.

**Comment by tej-kweku** [comment]
I have forked the project and fixed this issue as well as other bugs I found. [This is a link ](https://github.com/tej-kweku/php-mysql-admin-panel-generator)to the forked project.

**Comment by housamz** [comment]
@tej-kweku Thanks very much for your help in converting it to be PHP 7 compatible.
I didn't use PHP since I created this and didn't have the time to fix it.
