### ISSUE TITLE
Please wait

### ISSUE THREAD

**Issue by X-x-X-0** [housamz/php-mysql-admin-panel-generator#13]
for Some Reason it is leaving me on please wait but no files are being created or success msg in the example is not poping up,
![Screenshot_20201024-063854_Termius](https://user-images.githubusercontent.com/68131578/97080804-c00fd080-15c3-11eb-940d-9f407a583a34.jpg)
![Screenshot_20201024-063922_Chrome](https://user-images.githubusercontent.com/68131578/97080807-c43bee00-15c3-11eb-83c8-2ee7b2b50517.jpg)

I have no idea how to fix this

**Comment by naya-aastra** [comment]
Its may be because of the file permission.
Set the file permission to 777 and it works.

To set file permission use below command:
sudo chmod 777 -R php-mysql-admin-panel-generator
