### ISSUE TITLE
PHP 7.1 support?

### ISSUE THREAD

**Issue by malebuffy** [housamz/php-mysql-admin-panel-generator#14]
When I use PHP version 7.1 and above, I don't get the table data shown in the panel, only the number of entries. Any plans for PHP 7.1 support?

**Comment by malebuffy** [comment]
Found the answer. Change the below code and add ,MYSQLI_ASSOC.
   
 if(!is_null($object)){
        $row = mysqli_fetch_object($result,MYSQLI_ASSOC);
    }else{
        $row = mysqli_fetch_array($result,MYSQLI_ASSOC);
    }

**Comment by housamz** [comment]
Thank you very much.
I will add this in the coming version.
