### ISSUE TITLE
header already sent issue in save.php , when deleting values

### ISSUE THREAD

**Issue by thepanesar** [housamz/php-mysql-admin-panel-generator#8]
i have fixed the issue, by adding

//beginning of file
 ob_start();

//end of file
ob_end_flush();

![dev](https://user-images.githubusercontent.com/17591687/66980369-4dc20180-f0ce-11e9-9bc5-37d836646347.png)

**Comment by housamz** [comment]
I couldn't recreate this error, but thanks for the fix.
